<?php


/**
 * This class adds structure of 'cre8_flash_slider' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Oct 28 10:39:03 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.cre8FlashSliderPlugin.lib.model.map
 */
class Cre8FlashSliderMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.cre8FlashSliderPlugin.lib.model.map.Cre8FlashSliderMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Cre8FlashSliderPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Cre8FlashSliderPeer::TABLE_NAME);
		$tMap->setPhpName('Cre8FlashSlider');
		$tMap->setClassname('Cre8FlashSlider');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 60);

		$tMap->addColumn('FILENAME', 'Filename', 'VARCHAR', true, 128);

		$tMap->addColumn('URL', 'Url', 'VARCHAR', false, 255);

	} // doBuild()

} // Cre8FlashSliderMapBuilder
